# Generated by Django 3.0.7 on 2020-10-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulesv', '0003_comment2_comment3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='comment2',
            old_name='content',
            new_name='content2',
        ),
        migrations.RenameField(
            model_name='comment3',
            old_name='content',
            new_name='content3',
        ),
    ]
