# Generated by Django 3.0.7 on 2020-10-14 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelValid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('state_civil', models.CharField(max_length=50)),
                ('n_hijos', models.IntegerField()),
                ('lugar', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('posgrado', models.CharField(max_length=50)),
                ('time_ex', models.IntegerField()),
                ('work', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('sick', models.CharField(max_length=50)),
                ('who', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
