# Generated by Django 3.0.7 on 2021-01-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvalid',
            name='time_ex',
            field=models.CharField(max_length=50),
        ),
    ]
