# Generated by Django 3.0.7 on 2021-01-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formv', '0002_auto_20210103_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvalid',
            name='time_ex',
            field=models.IntegerField(),
        ),
    ]
